// Auto-generated file created by react-native-storybook-loader
// Do not edit.
//
// https://github.com/elderfo/react-native-storybook-loader.git

function loadStories() {
  require('../src/atoms/Checkbox/index.stories')
  require('../src/atoms/Heading/index.stories')
  require('../src/atoms/Like/index.stories')
  require('../src/atoms/Placeholder/index.stories')
  require('../src/atoms/PrimaryButton/index.stories')
  require('../src/atoms/RadioButton/index.stories')
  require('../src/atoms/Rating/index.stories')
  require('../src/atoms/Recommendation/index.stories')
  require('../src/atoms/Ribbon/index.stories')
  require('../src/atoms/RoundedButton/index.stories')
  require('../src/atoms/Switch/index.stories')
  require('../src/atoms/Text/index.stories')
  require('../src/atoms/WineBottlePicture/index.stories')
  require('../src/atoms/WineBottlePrice/index.stories')
  require('../src/atoms/WineInfo/index.stories')
  require('../src/atoms/WineShopName/index.stories')
  require('../src/molecules/Auth/CheckedIcon.stories')
  require('../src/molecules/Auth/ConsentCheckBox.stories')
  require('../src/molecules/Auth/GoBackArrowIcon.stories')
  require('../src/molecules/Auth/LabeledDatePicker.stories')
  require('../src/molecules/Auth/UncheckedIcon.stories')
  require('../src/molecules/CityChooser/index.stories')
  require('../src/molecules/ConfirmPopUp/index.stories')
  require('../src/molecules/Countdown/index.stories')
  require('../src/molecules/FavoritesPlaceholder/index.stories')
  require('../src/molecules/FilterButton/Color.stories')
  require('../src/molecules/FilterButton/Country.stories')
  require('../src/molecules/FilterButton/Favorites.stories')
  require('../src/molecules/FilterButton/Price.stories')
  require('../src/molecules/FilterButton/Recomemended.stories')
  require('../src/molecules/FilterButton/Sugar.stories')
  require('../src/molecules/Header/index.stories')
  require('../src/molecules/LabeledCheckbox/index.stories')
  require('../src/molecules/LabeledInput/index.stories')
  require('../src/molecules/LabeledRadioButton/index.stories')
  require('../src/molecules/PriceInput/index.stories')
  require('../src/molecules/SearchInput/index.stories')
  require('../src/molecules/WineCard/index.stories')
  require('../src/molecules/WineCard/Loader.stories')
  require('../src/molecules/WineReviewCard/index.stories')
  require('../src/organisms/CatalogView/index.stories')
  require('../src/organisms/ExtraOptions/index.stories')
  require('../src/organisms/FavoritesToolbar/index.stories')
  require('../src/organisms/FiltersBar/index.stories')
  require('../src/organisms/FilterSheet/index.stories')
  require('../src/organisms/RecommendationBlock/index.stories')
  require('../src/organisms/WineDescription/index.stories')
  require('../src/organisms/WineReviews/index.stories')
}

const stories = [
  '../src/atoms/Checkbox/index.stories',
  '../src/atoms/Heading/index.stories',
  '../src/atoms/Like/index.stories',
  '../src/atoms/Placeholder/index.stories',
  '../src/atoms/PrimaryButton/index.stories',
  '../src/atoms/RadioButton/index.stories',
  '../src/atoms/Rating/index.stories',
  '../src/atoms/Recommendation/index.stories',
  '../src/atoms/Ribbon/index.stories',
  '../src/atoms/RoundedButton/index.stories',
  '../src/atoms/Switch/index.stories',
  '../src/atoms/Text/index.stories',
  '../src/atoms/WineBottlePicture/index.stories',
  '../src/atoms/WineBottlePrice/index.stories',
  '../src/atoms/WineInfo/index.stories',
  '../src/atoms/WineShopName/index.stories',
  '../src/molecules/Auth/CheckedIcon.stories',
  '../src/molecules/Auth/ConsentCheckBox.stories',
  '../src/molecules/Auth/GoBackArrowIcon.stories',
  '../src/molecules/Auth/LabeledDatePicker.stories',
  '../src/molecules/Auth/UncheckedIcon.stories',
  '../src/molecules/CityChooser/index.stories',
  '../src/molecules/ConfirmPopUp/index.stories',
  '../src/molecules/Countdown/index.stories',
  '../src/molecules/FavoritesPlaceholder/index.stories',
  '../src/molecules/FilterButton/Color.stories',
  '../src/molecules/FilterButton/Country.stories',
  '../src/molecules/FilterButton/Favorites.stories',
  '../src/molecules/FilterButton/Price.stories',
  '../src/molecules/FilterButton/Recomemended.stories',
  '../src/molecules/FilterButton/Sugar.stories',
  '../src/molecules/Header/index.stories',
  '../src/molecules/LabeledCheckbox/index.stories',
  '../src/molecules/LabeledInput/index.stories',
  '../src/molecules/LabeledRadioButton/index.stories',
  '../src/molecules/PriceInput/index.stories',
  '../src/molecules/SearchInput/index.stories',
  '../src/molecules/WineCard/index.stories',
  '../src/molecules/WineCard/Loader.stories',
  '../src/molecules/WineReviewCard/index.stories',
  '../src/organisms/CatalogView/index.stories',
  '../src/organisms/ExtraOptions/index.stories',
  '../src/organisms/FavoritesToolbar/index.stories',
  '../src/organisms/FiltersBar/index.stories',
  '../src/organisms/FilterSheet/index.stories',
  '../src/organisms/RecommendationBlock/index.stories',
  '../src/organisms/WineDescription/index.stories',
  '../src/organisms/WineReviews/index.stories',
]

module.exports = {
  loadStories,
  stories,
}
