name: ESLint

on:
  pull_request:
    branches: [ develop, master ]

jobs:
  lint:
    name: ESLint
    runs-on: ubuntu-latest


    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Cache deps
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-build-${{ env.cache-name }}-
            ${{ runner.OS}}-build
            ${{ runner.OS }}-

      - name: Install deps
        run: yarn install
      
      - name: Lint
        run: yarn lint
